language: php
php:
  - '5.5'
  - '5.6'

notifications:
    on_success: never
    on_failure: always

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit